"""init

Revision ID: c8281c1ce2d4
Revises: 
Create Date: 2025-08-22 15:02:51.750265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8281c1ce2d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mcp_servers_id'), 'mcp_servers', ['id'], unique=False)
    op.create_table('message_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_roles_code'), 'message_roles', ['code'], unique=True)
    op.create_table('message_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_statuses_code'), 'message_statuses', ['code'], unique=True)
    op.create_table('model_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_providers_code'), 'model_providers', ['code'], unique=True)
    op.create_table('model_purposes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_purposes_code'), 'model_purposes', ['code'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_code'), 'user_roles', ['code'], unique=True)
    op.create_table('embedding_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('dtype', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('dimension > 0', name='ck_embed_spec_dimension_pos'),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'model', name='uq_embed_spec_provider_model')
    )
    op.create_index('ix_embed_spec_active', 'embedding_specs', ['is_active'], unique=False)
    op.create_index('ix_embed_spec_provider_model', 'embedding_specs', ['provider_id', 'model'], unique=False)
    op.create_index(op.f('ix_embedding_specs_id'), 'embedding_specs', ['id'], unique=False)
    op.create_index(op.f('ix_embedding_specs_provider_id'), 'embedding_specs', ['provider_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['user_roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('embedding_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['embedding_id'], ['embedding_specs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_embedding_id'), 'collections', ['embedding_id'], unique=False)
    op.create_table('model_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('endpoint_url', sa.String(length=255), nullable=True),
    sa.Column('purpose_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purpose_id'], ['model_purposes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'alias', name='uq_modelkey_owner_alias'),
    sa.UniqueConstraint('owner_id', 'provider_id', 'model', 'endpoint_url', name='uq_modelkey_owner_provider_model_endpoint')
    )
    op.create_index(op.f('ix_model_api_keys_id'), 'model_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_model_api_keys_is_active'), 'model_api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_model_api_keys_is_public'), 'model_api_keys', ['is_public'], unique=False)
    op.create_index(op.f('ix_model_api_keys_owner_id'), 'model_api_keys', ['owner_id'], unique=False)
    op.create_index(op.f('ix_model_api_keys_provider_id'), 'model_api_keys', ['provider_id'], unique=False)
    op.create_index(op.f('ix_model_api_keys_purpose_id'), 'model_api_keys', ['purpose_id'], unique=False)
    op.create_index('ix_modelkey_provider_purpose', 'model_api_keys', ['provider_id', 'purpose_id'], unique=False)
    op.create_index('ix_modelkey_public_active', 'model_api_keys', ['is_public', 'is_active'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_model_key_id', sa.Integer(), nullable=True),
    sa.Column('default_params', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['default_model_key_id'], ['model_api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conv_user_created', 'conversations', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversations_default_model_key_id'), 'conversations', ['default_model_key_id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('conversation_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mcp_server_id', sa.Integer(), nullable=True),
    sa.Column('model_api_key_id', sa.Integer(), nullable=True),
    sa.Column('model_provider_id', sa.Integer(), nullable=True),
    sa.Column('model_provider_code', sa.String(length=32), nullable=True),
    sa.Column('model_model', sa.String(length=100), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_api_key_id'], ['model_api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_provider_id'], ['model_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['message_roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_id'], ['message_statuses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_histories_conversation_id'), 'conversation_histories', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_histories_id'), 'conversation_histories', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_histories_role_id'), 'conversation_histories', ['role_id'], unique=False)
    op.create_index(op.f('ix_conversation_histories_status_id'), 'conversation_histories', ['status_id'], unique=False)
    op.create_index('ix_hist_conv_ts', 'conversation_histories', ['conversation_id', 'timestamp'], unique=False)
    op.create_index('ix_hist_mcp', 'conversation_histories', ['mcp_server_id'], unique=False)
    op.create_index('ix_hist_model_key', 'conversation_histories', ['model_api_key_id'], unique=False)
    op.create_table('conversation_mcp_server',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('mcp_server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'mcp_server_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_mcp_server')
    op.drop_index('ix_hist_model_key', table_name='conversation_histories')
    op.drop_index('ix_hist_mcp', table_name='conversation_histories')
    op.drop_index('ix_hist_conv_ts', table_name='conversation_histories')
    op.drop_index(op.f('ix_conversation_histories_status_id'), table_name='conversation_histories')
    op.drop_index(op.f('ix_conversation_histories_role_id'), table_name='conversation_histories')
    op.drop_index(op.f('ix_conversation_histories_id'), table_name='conversation_histories')
    op.drop_index(op.f('ix_conversation_histories_conversation_id'), table_name='conversation_histories')
    op.drop_table('conversation_histories')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_default_model_key_id'), table_name='conversations')
    op.drop_index('ix_conv_user_created', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_modelkey_public_active', table_name='model_api_keys')
    op.drop_index('ix_modelkey_provider_purpose', table_name='model_api_keys')
    op.drop_index(op.f('ix_model_api_keys_purpose_id'), table_name='model_api_keys')
    op.drop_index(op.f('ix_model_api_keys_provider_id'), table_name='model_api_keys')
    op.drop_index(op.f('ix_model_api_keys_owner_id'), table_name='model_api_keys')
    op.drop_index(op.f('ix_model_api_keys_is_public'), table_name='model_api_keys')
    op.drop_index(op.f('ix_model_api_keys_is_active'), table_name='model_api_keys')
    op.drop_index(op.f('ix_model_api_keys_id'), table_name='model_api_keys')
    op.drop_table('model_api_keys')
    op.drop_index(op.f('ix_collections_embedding_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_embedding_specs_provider_id'), table_name='embedding_specs')
    op.drop_index(op.f('ix_embedding_specs_id'), table_name='embedding_specs')
    op.drop_index('ix_embed_spec_provider_model', table_name='embedding_specs')
    op.drop_index('ix_embed_spec_active', table_name='embedding_specs')
    op.drop_table('embedding_specs')
    op.drop_index(op.f('ix_user_roles_code'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_model_purposes_code'), table_name='model_purposes')
    op.drop_table('model_purposes')
    op.drop_index(op.f('ix_model_providers_code'), table_name='model_providers')
    op.drop_table('model_providers')
    op.drop_index(op.f('ix_message_statuses_code'), table_name='message_statuses')
    op.drop_table('message_statuses')
    op.drop_index(op.f('ix_message_roles_code'), table_name='message_roles')
    op.drop_table('message_roles')
    op.drop_index(op.f('ix_mcp_servers_id'), table_name='mcp_servers')
    op.drop_table('mcp_servers')
    # ### end Alembic commands ###
