"""alter conversation history

Revision ID: 17038bf1be51
Revises: 532f328f3424
Create Date: 2025-09-04 09:59:47.694619

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "17038bf1be51"
down_revision: Union[str, Sequence[str], None] = "532f328f3424"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation_histories",
        sa.Column("tool_call_id", sa.String(length=64), nullable=True),
    )
    op.alter_column(
        "conversation_histories", "content", existing_type=sa.TEXT(), nullable=True
    )
    op.create_index(
        "ix_hist_tool_call",
        "conversation_histories",
        ["conversation_id", "tool_call_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_hist_tool_call", table_name="conversation_histories")
    op.alter_column(
        "conversation_histories", "content", existing_type=sa.TEXT(), nullable=False
    )
    op.drop_column("conversation_histories", "tool_call_id")
