"""add tools history

Revision ID: 532f328f3424
Revises: ef0e27a04461
Create Date: 2025-08-25 14:39:49.845651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "532f328f3424"
down_revision: Union[str, Sequence[str], None] = "ef0e27a04461"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation_histories",
        sa.Column("tool_name", sa.String(length=256), nullable=True),
    )
    op.add_column(
        "conversation_histories", sa.Column("tool_input", sa.JSON(), nullable=True)
    )
    op.add_column(
        "conversation_histories", sa.Column("tool_output", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversation_histories", "tool_output")
    op.drop_column("conversation_histories", "tool_input")
    op.drop_column("conversation_histories", "tool_name")

    # ### end Alembic commands ###
